/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package resturent;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;



/**
 *
 * @author Admin
 */
public class AddDate extends javax.swing.JFrame {
Connection co;
            Statement st;
    /**
     * Creates new form AddDate
     */
    public AddDate() {
        initComponents();
        
         this.setSize(625,660);
         this.setResizable(false);
        
         
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tname = new javax.swing.JTextField();
        label = new javax.swing.JLabel();
        time = new javax.swing.JTextField();
        lable3 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tabel_num = new javax.swing.JTextField();
        label2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("حجز موعد");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 10, 85, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("عدد الطاولات");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(500, 120, 86, 17);

        ID.setBackground(new java.awt.Color(204, 204, 204));
        ID.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        getContentPane().add(ID);
        ID.setBounds(300, 80, 180, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("اسم الزبون");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(510, 200, 73, 17);

        tname.setBackground(new java.awt.Color(204, 204, 204));
        tname.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        getContentPane().add(tname);
        tname.setBounds(300, 200, 180, 22);

        label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label.setText("موعد الحجز");
        getContentPane().add(label);
        label.setBounds(510, 160, 76, 17);

        time.setBackground(new java.awt.Color(204, 204, 204));
        time.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeActionPerformed(evt);
            }
        });
        getContentPane().add(time);
        time.setBounds(410, 160, 70, 22);

        lable3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lable3.setText("رقم الهاتف");
        getContentPane().add(lable3);
        lable3.setBounds(510, 240, 70, 17);

        phone.setBackground(new java.awt.Color(204, 204, 204));
        phone.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        getContentPane().add(phone);
        phone.setBounds(300, 240, 180, 22);

        save.setBackground(new java.awt.Color(73, 69, 72));
        save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setText("تخزين");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(330, 280, 74, 33);

        back.setBackground(new java.awt.Color(73, 69, 72));
        back.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("رجوع");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(0, 570, 90, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("رقم الهوية");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(510, 80, 70, 17);

        tabel_num.setBackground(new java.awt.Color(204, 204, 204));
        tabel_num.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tabel_num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabel_numActionPerformed(evt);
            }
        });
        getContentPane().add(tabel_num);
        tabel_num.setBounds(300, 120, 180, 22);

        label2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resturent/date.png"))); // NOI18N
        getContentPane().add(label2);
        label2.setBounds(0, 100, 610, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed

       tabel_num.setText("");
       phone.setText("");
       tname.setText("");
       ID.setText("");
       time.setText("");
       this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed
    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:id.setText("");
        try{
              DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            String host="jdbc:oracle:thin:@localhost:1522:orcl";
            String name= "project";
            String pass="123456";
             co=DriverManager.getConnection(host, name, pass);
             st=co.createStatement(/*ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE*/);
            String SQL ="insert into RESERVATION values("+this.ID.getText()+",'"+this.tname.getText()+"',"+this.phone.getText()+","+this.tabel_num.getText()+",'"+this.time.getText()+"')";
           st.executeUpdate(SQL);
           co.commit();
           co.close();
        }catch(SQLException aa){
            
        }
       phone.setText("");
       tname.setText("");
       ID.setText("");
       time.setText("");
       tabel_num.setText("");
    }//GEN-LAST:event_saveActionPerformed

    private void tabel_numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabel_numActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tabel_numActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        AddDate date = new AddDate();
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                date.setVisible(true);
                date.setSize(625,660);
                date.setResizable(false);
            }
        });
    }
    
    

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel label;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel lable3;
    private javax.swing.JTextField phone;
    private javax.swing.JButton save;
    private javax.swing.JTextField tabel_num;
    private javax.swing.JTextField time;
    private javax.swing.JTextField tname;
    // End of variables declaration//GEN-END:variables
}
