/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package resturent;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Delivery extends javax.swing.JFrame {
Connection co;
            Statement st;
    /**
     * Creates new form Delivery
     */
    public Delivery() {
        initComponents();
        this.setSize(405,665);
        this.setResizable(false);
       /* name.setBackground(new Color(0,0,0,64));
        phone.setBackground(new Color(0,0,0,64));
        address1.setBackground(new Color(0,0,0,64));
        address2.setBackground(new Color(0,0,0,64));*/
    }
    
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        address1 = new javax.swing.JTextField();
        address2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        mainOrder = new javax.swing.JButton();
        drink = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setText("Delivery");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 10, 101, 29);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("معلومات الطلب :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(260, 190, 108, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("اسم الشخص");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(280, 240, 84, 16);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("رقم الهاتف");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(300, 290, 65, 16);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setText("العنوان  1");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(300, 340, 58, 16);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setText("العنوان  2");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(300, 390, 58, 16);

        name.setBackground(new java.awt.Color(31, 153, 193));
        name.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name);
        name.setBounds(20, 230, 243, 30);

        phone.setBackground(new java.awt.Color(31, 153, 193));
        phone.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        phone.setForeground(new java.awt.Color(255, 255, 255));
        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });
        getContentPane().add(phone);
        phone.setBounds(20, 280, 243, 32);

        address1.setBackground(new java.awt.Color(31, 153, 193));
        address1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        address1.setForeground(new java.awt.Color(255, 255, 255));
        address1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address1ActionPerformed(evt);
            }
        });
        getContentPane().add(address1);
        address1.setBounds(20, 330, 243, 33);

        address2.setBackground(new java.awt.Color(31, 153, 193));
        address2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        address2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(address2);
        address2.setBounds(20, 380, 243, 33);

        jButton1.setBackground(new java.awt.Color(73, 69, 72));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("تخزين");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 440, 85, 35);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("الطلب :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(320, 80, 49, 17);

        mainOrder.setBackground(new java.awt.Color(74, 69, 72));
        mainOrder.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        mainOrder.setForeground(new java.awt.Color(255, 255, 255));
        mainOrder.setText("قائمة الطعام");
        mainOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mainOrderMouseReleased(evt);
            }
        });
        mainOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainOrderActionPerformed(evt);
            }
        });
        getContentPane().add(mainOrder);
        mainOrder.setBounds(130, 80, 135, 37);

        drink.setBackground(new java.awt.Color(73, 69, 72));
        drink.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        drink.setForeground(new java.awt.Color(255, 255, 255));
        drink.setText("قائمة المشروبات");
        drink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drinkActionPerformed(evt);
            }
        });
        getContentPane().add(drink);
        drink.setBounds(130, 130, 135, 37);

        back.setBackground(new java.awt.Color(73, 69, 72));
        back.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("رجوع");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(0, 580, 90, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resturent/pngtree-cartoon-minimalist-catering-gourmet-takeaway-poster-background-image_188051.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -20, 400, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainOrderMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainOrderMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_mainOrderMouseReleased
MainOrder m = new MainOrder();
Drinks D = new Drinks();
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  try{
              DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            String host="jdbc:oracle:thin:@localhost:1522:orcl";
            String name= "project";
            String pass="123456";
             co=DriverManager.getConnection(host, name, pass);
             st=co.createStatement(/*ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE*/);
            String SQL ="insert into DELIVERY values('"+this.name.getText()+"',"+this.phone.getText()+",'"+this.address1.getText()+"','"+this.address2.getText()+"','"+this.m.getA()+"','"+this.D.getB()+"')";
           st.executeUpdate(SQL);
           co.commit();
           co.close();
        }catch(SQLException aa){
            
        }
        address1.setText("");
        address2.setText("");
        name.setText("");
        phone.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed

        address1.setText("");
        address2.setText("");
        name.setText("");
        phone.setText("");
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void mainOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainOrderActionPerformed
        if(order == null)
            order = new MainOrder();
        if(!order.isVisible())
            order.setVisible(true);
    }//GEN-LAST:event_mainOrderActionPerformed

    private void drinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drinkActionPerformed
        if(drinks == null)
            drinks = new Drinks();
        if(!drinks.isVisible())
            drinks.setVisible(true);
    }//GEN-LAST:event_drinkActionPerformed

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void address1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address1ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        Delivery del = new Delivery();
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                del.setVisible(true);
                del.setSize(405,665);
                del.setResizable(false);
            }
        });
    }

    MainOrder order;
    Drinks drinks;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address1;
    private javax.swing.JTextField address2;
    private javax.swing.JButton back;
    private javax.swing.JButton drink;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton mainOrder;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phone;
    // End of variables declaration//GEN-END:variables
}
