/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package resturent;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import oracle.jdbc.pool.OracleDataSource;
import oracle.sql.NUMBER;

/**
 *
 * @author Admin
 */
public class department1 extends javax.swing.JFrame {
Connection co;
            Statement st;
            private int i =0;
    /**
     * Creates new form department1
     */
    public department1() {
        initComponents();
        
        this.setSize(1140,760);
        this.setResizable(false);
                
        Number_table.setEditable(false);
        DeliveryAv.setSelected(true);
        active = true;
         try{
            
            //  DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            OracleDataSource oda = new OracleDataSource();
            String host="jdbc:oracle:thin:@localhost:1522:orcl";
            String name= "project";
            String pass="123456";
            oda.setURL(host);
            oda.setUser(name);
            oda.setPassword(pass);
              co=oda.getConnection();
             st=co.createStatement(/*ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE*/);
            ResultSet rt=st.executeQuery("Select * from reservation");
           
           while( rt.next()){
            i++;
           }
           Number_table.setText("        "+Integer.toString(i));
            co.close();
           
        }catch(Exception aa){
            Logger.getLogger(Dates.class.getName()).log(Level.SEVERE,null,aa);
        }
        
    }

   
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Button1 = new javax.swing.JButton();
        Button2 = new javax.swing.JButton();
        Button3 = new javax.swing.JButton();
        Button4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        Number_table = new javax.swing.JTextField();
        DeliveryAv = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        addOrder = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("الإستقبال");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(500, 0, 120, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("الخدمات");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(700, 110, 90, 22);

        Button1.setBackground(new java.awt.Color(51, 51, 51));
        Button1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Button1.setForeground(new java.awt.Color(255, 255, 255));
        Button1.setText("حجز موعد");
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });
        getContentPane().add(Button1);
        Button1.setBounds(550, 110, 140, 50);

        Button2.setBackground(new java.awt.Color(51, 51, 51));
        Button2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Button2.setForeground(new java.awt.Color(255, 255, 255));
        Button2.setText("طلب توصيل");
        Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button2ActionPerformed(evt);
            }
        });
        getContentPane().add(Button2);
        Button2.setBounds(380, 110, 150, 50);

        Button3.setBackground(new java.awt.Color(51, 51, 51));
        Button3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Button3.setForeground(new java.awt.Color(255, 255, 255));
        Button3.setText("عرض الحجوزات");
        Button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button3ActionPerformed(evt);
            }
        });
        getContentPane().add(Button3);
        Button3.setBounds(550, 180, 140, 50);

        Button4.setBackground(new java.awt.Color(51, 51, 51));
        Button4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Button4.setForeground(new java.awt.Color(255, 255, 255));
        Button4.setText("عرض الطلبات");
        Button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button4ActionPerformed(evt);
            }
        });
        getContentPane().add(Button4);
        Button4.setBounds(380, 180, 150, 50);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("خدمة التوصيل ");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(650, 390, 150, 22);

        Back.setBackground(new java.awt.Color(51, 51, 51));
        Back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Back.setForeground(new java.awt.Color(255, 255, 255));
        Back.setText("رجوع");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back);
        Back.setBounds(350, 620, 110, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("عدد الحجوزات ");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(650, 300, 140, 22);

        Number_table.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number_tableActionPerformed(evt);
            }
        });
        getContentPane().add(Number_table);
        Number_table.setBounds(570, 300, 60, 30);

        DeliveryAv.setBackground(new java.awt.Color(51, 51, 51));
        DeliveryAv.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        DeliveryAv.setForeground(new java.awt.Color(255, 255, 255));
        DeliveryAv.setText("خدمة التوصيل متوفرة");
        DeliveryAv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeliveryAvActionPerformed(evt);
            }
        });
        getContentPane().add(DeliveryAv);
        DeliveryAv.setBounds(430, 380, 200, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("الطلبات الداخلية");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(640, 500, 140, 22);

        addOrder.setBackground(new java.awt.Color(51, 51, 51));
        addOrder.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addOrder.setForeground(new java.awt.Color(255, 255, 255));
        addOrder.setText("إضافة طلب");
        addOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrderActionPerformed(evt);
            }
        });
        getContentPane().add(addOrder);
        addOrder.setBounds(480, 490, 150, 50);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resturent/واجهة استقبال.jpg"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 0, 1140, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Number_tableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number_tableActionPerformed
        // TODO add your handling code here:
       
    
    }//GEN-LAST:event_Number_tableActionPerformed

    private void DeliveryAvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeliveryAvActionPerformed
       if(active == false){
           active = true;
           DeliveryAv.setText("خدمة التوصيل متوفرة");
       }
       else { active = false;
       DeliveryAv.setText("خدمة التوصيل غير متوفرة");
       }
    }//GEN-LAST:event_DeliveryAvActionPerformed

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
        if(add == null)
            add = new AddDate();
        if(!add.isVisible()){
            //add = new AddDate();
            add.setVisible(true);
        }
    }//GEN-LAST:event_Button1ActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        log = new login();
        log.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackActionPerformed

    private void Button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button4ActionPerformed
        if(show == null)
            show = new showDelivery();
        if(!show.isVisible()){
           // show = new showDelivery();
            show.setVisible(true);
        }
    }//GEN-LAST:event_Button4ActionPerformed

    private void Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button2ActionPerformed
        if(active == false)
            JOptionPane.showMessageDialog(null, "آسف ,خدمة التوصيل غير متوفرة حالياً");
        else {
            if(del == null)
            del = new Delivery();
        if(!del.isVisible()){
            //del = new Delivery();
            del.setVisible(true);
        }
        }
          
    }//GEN-LAST:event_Button2ActionPerformed

    private void Button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button3ActionPerformed
        if(date == null)
            date = new Dates();
        if(!date.isVisible()){
            //date = new Dates();
            date.setVisible(true);
        }
        
    }//GEN-LAST:event_Button3ActionPerformed

    private void addOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrderActionPerformed
        if(in == null)
            in = new InerOrder();
        if(!in.isVisible()){
            
            in.setVisible(true);
        }
    }//GEN-LAST:event_addOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        department1 dep = new department1();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dep.setVisible(true);
                dep.setSize(1140,760);
                dep.setResizable(false);
            }
        });
    }
     login log;
     AddDate add;
     Delivery del;
     Dates date;
     showDelivery show;
     InerOrder in;
     private int number;
     private boolean active;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Button1;
    private javax.swing.JButton Button2;
    private javax.swing.JButton Button3;
    private javax.swing.JButton Button4;
    private javax.swing.JToggleButton DeliveryAv;
    private javax.swing.JTextField Number_table;
    private javax.swing.JButton addOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    
}
