/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package resturent;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import oracle.jdbc.pool.OracleDataSource;

/**
 *
 * @author Admin
 */
public class department2 extends javax.swing.JFrame {
 Connection co;
            Statement st;
            ResultSet rt;
    /**
     * Creates new form department2
     */
    public department2() {
        initComponents();
        orderArea.setEditable(false);
        //searchText.setBackground(new Color(0,0,0,64));
         this.setSize(1240,760);
         this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        drinkMenu = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderArea = new javax.swing.JTextArea();
        button1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        searchText = new javax.swing.JTextField();
        search1 = new javax.swing.JButton();
        done1 = new javax.swing.JButton();
        foodMenu = new javax.swing.JButton();
        back = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        search2 = new javax.swing.JButton();
        searchText1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        done2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("المطبخ        ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(530, 10, 220, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("قوائم الطعام و المشروبات :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(990, 110, 232, 22);

        drinkMenu.setBackground(new java.awt.Color(255, 255, 204));
        drinkMenu.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        drinkMenu.setText("قائمة المشروبات");
        drinkMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drinkMenuActionPerformed(evt);
            }
        });
        getContentPane().add(drinkMenu);
        drinkMenu.setBounds(640, 100, 140, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("الطلبات :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(1140, 170, 77, 22);

        orderArea.setColumns(20);
        orderArea.setRows(5);
        jScrollPane1.setViewportView(orderArea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(840, 200, 383, 480);

        button1.setBackground(new java.awt.Color(255, 255, 204));
        button1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        button1.setText("عرض الطلبات الداخلية");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1);
        button1.setBounds(640, 420, 180, 34);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("البحث عن الطلب (حسب الرقم ) :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(600, 470, 220, 17);

        searchText.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        searchText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextActionPerformed(evt);
            }
        });
        getContentPane().add(searchText);
        searchText.setBounds(580, 500, 240, 31);

        search1.setBackground(new java.awt.Color(255, 255, 204));
        search1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        search1.setText("بحث");
        search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search1ActionPerformed(evt);
            }
        });
        getContentPane().add(search1);
        search1.setBounds(480, 500, 80, 31);

        done1.setBackground(new java.awt.Color(255, 255, 204));
        done1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        done1.setText("تم اعداد الطلب");
        done1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                done1ActionPerformed(evt);
            }
        });
        getContentPane().add(done1);
        done1.setBounds(680, 550, 137, 34);

        foodMenu.setBackground(new java.awt.Color(255, 255, 204));
        foodMenu.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        foodMenu.setText("قائمة الطعام");
        foodMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodMenuActionPerformed(evt);
            }
        });
        getContentPane().add(foodMenu);
        foodMenu.setBounds(810, 100, 140, 40);

        back.setBackground(new java.awt.Color(255, 255, 204));
        back.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        back.setText("رجوع");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(530, 670, 100, 40);

        button2.setBackground(new java.awt.Color(255, 255, 204));
        button2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        button2.setText("عرض الطلبات الخارجية");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        getContentPane().add(button2);
        button2.setBounds(640, 210, 180, 34);

        search2.setBackground(new java.awt.Color(255, 255, 204));
        search2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        search2.setText("بحث");
        search2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search2ActionPerformed(evt);
            }
        });
        getContentPane().add(search2);
        search2.setBounds(480, 290, 80, 31);

        searchText1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        searchText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchText1ActionPerformed(evt);
            }
        });
        getContentPane().add(searchText1);
        searchText1.setBounds(580, 290, 240, 31);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("البحث عن طلب (حسب الاسم) :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(610, 260, 208, 17);

        done2.setBackground(new java.awt.Color(255, 255, 204));
        done2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        done2.setText("تم اعداد الطلب");
        done2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                done2ActionPerformed(evt);
            }
        });
        getContentPane().add(done2);
        done2.setBounds(680, 340, 137, 34);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(440, 400, 380, 10);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resturent/444634-PEMTQB-849.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 1292, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void drinkMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drinkMenuActionPerformed
        if(d == null)
            d = new EditDrink();
        if(!d.isVisible())
            
            d.setVisible(true);
    }//GEN-LAST:event_drinkMenuActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        log = new login();
        log.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void foodMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodMenuActionPerformed
        if(e == null)
            e = new EditMenu();
        if(!e.isVisible())
            
            e.setVisible(true);
    }//GEN-LAST:event_foodMenuActionPerformed

    private void done2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_done2ActionPerformed
 try{
              DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            String host="jdbc:oracle:thin:@localhost:1522:orcl";
            String name= "project";
            String pass="123456";
             co=DriverManager.getConnection(host, name, pass);
             st=co.createStatement(/*ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE*/);
            String SQL ="DELETE FROM DELIVERY where ALL_NAME='"+this.searchText1.getText()+"'";
           st.executeUpdate(SQL);
           co.commit();
           co.close();
        }catch(SQLException aa){
            
        }
        searchText1.setText("");
    }//GEN-LAST:event_done2ActionPerformed

    private void searchTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTextActionPerformed

    private void done1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_done1ActionPerformed
 try{
              DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            String host="jdbc:oracle:thin:@localhost:1522:orcl";
            String name= "project";
            String pass="123456";
             co=DriverManager.getConnection(host, name, pass);
             st=co.createStatement(/*ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE*/);
            String SQL ="DELETE FROM INERORDER where TABLE_NUM ='"+this.searchText.getText()+"'";
           st.executeUpdate(SQL);
           co.commit();
           co.close();
        }catch(SQLException aa){
            
        }
        searchText.setText("");
    }//GEN-LAST:event_done1ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        try{
            //  DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            OracleDataSource oda = new OracleDataSource();
            String host="jdbc:oracle:thin:@localhost:1522:orcl";
            String name= "project";
            String pass="123456";
            oda.setURL(host);
            oda.setUser(name);
            oda.setPassword(pass);
              co=oda.getConnection();
             st=co.createStatement(/*ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE*/);
             rt=st.executeQuery("Select * from INERORDER");
            //this.orderArea.setText("Tabel Number"+"          "+"Drink Order"+"                "+"Food Order"+"\n");
           // this.orderArea.append("---------------------------------------------------------------------------"+"\n");
           while( rt.next()){
            int a= rt.getInt(1);
            String b= rt.getString(2);
            String c= rt.getString(3);
            
            this.orderArea.append("Tabel Number :  "+ a +"\n"+"Drink Order :  "+b+"Food Order :  "+c);
            this.orderArea.append("---------------------------------------------------------------------------"+"\n");
           }
            co.close();
           
        }catch(Exception aa){
            Logger.getLogger(Dates.class.getName()).log(Level.SEVERE,null,aa);
        }
        
    }//GEN-LAST:event_button1ActionPerformed

    private void search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search1ActionPerformed
        // TODO add your handling code here:
        try{
            //  DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            OracleDataSource oda = new OracleDataSource();
            String host="jdbc:oracle:thin:@localhost:1522:orcl";
            String name= "project";
            String pass="123456";
            oda.setURL(host);
            oda.setUser(name);
            oda.setPassword(pass);
              co=oda.getConnection();
             st=co.createStatement(/*ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE*/);
             rt=st.executeQuery("Select * from INERORDER where TABLE_NUM='"+this.searchText.getText()+"'");
            this.orderArea.setText("Tabel Number"+"          "+"Drink Order"+"            "+"Food Order"+"\n");
            this.orderArea.append("---------------------------------------------------------------------------"+"\n");
           while( rt.next()){
            int a= rt.getInt(1);
            String b= rt.getString(2);
            String c= rt.getString(3);
            
            this.orderArea.append(a+"               "+b+"          "+c+"\n");
           }
            co.close();
           
        }catch(Exception aa){
            Logger.getLogger(Dates.class.getName()).log(Level.SEVERE,null,aa);
        }
        
    }//GEN-LAST:event_search1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
      try{
            //  DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            OracleDataSource oda = new OracleDataSource();
            String host="jdbc:oracle:thin:@localhost:1522:orcl";
            String name= "project";
            String pass="123456";
            oda.setURL(host);
            oda.setUser(name);
            oda.setPassword(pass);
              co=oda.getConnection();
             st=co.createStatement(/*ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE*/);
             rt=st.executeQuery("Select * from DELIVERY");
            this.orderArea.setText("Name"+"          "+"Phone"+"            "+"Address 1"+"           "+"Address 2"+"          "+"Order"+"Drink"+"\n");
            this.orderArea.append("-----------------------------------------------------------------------------------------"+"\n");
           while( rt.next()){
            String a= rt.getString(1);
            int b= rt.getInt(2);
            String c= rt.getString(3);
            String d= rt.getString(4);
            String e= rt.getString(5);
            String f= rt.getString(6);
            this.orderArea.append(a+"          "+b+"          "+c+"          "+d+"             "+e+"   " +f+"\n");
           }
            co.close();
           
        }catch(Exception aa){
            Logger.getLogger(Dates.class.getName()).log(Level.SEVERE,null,aa);
        }
    }//GEN-LAST:event_button2ActionPerformed

    private void search2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search2ActionPerformed
        // TODO add your handling code here:
        try{
            //  DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            OracleDataSource oda = new OracleDataSource();
            String host="jdbc:oracle:thin:@localhost:1522:orcl";
            String name= "project";
            String pass="123456";
            oda.setURL(host);
            oda.setUser(name);
            oda.setPassword(pass);
              co=oda.getConnection();
             st=co.createStatement(/*ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE*/);
            ResultSet rt=st.executeQuery("Select * from DELIVERY where ALL_NAME='"+this.searchText1.getText()+"'");
            this.orderArea.setText("Name"+"          "+"Phone"+"            "+"Address 1"+"           "+"Address 2"+"          "+"Order"+"         "+"Drink"+"\n");
            this.orderArea.append("-----------------------------------------------------------------------------------------"+"\n");
           while( rt.next()){
            String a= rt.getString(1);
            int b= rt.getInt(2);
            String c= rt.getString(3);
            String d= rt.getString(4);
            String e= rt.getString(5);
            String f= rt.getString(6);
            this.orderArea.append(a+"          "+b+"          "+c+"          "+d+"              "+e+"   " +f+"\n");
           }
            co.close();
           
        }catch(Exception aa){
            Logger.getLogger(Dates.class.getName()).log(Level.SEVERE,null,aa);
        }
        
    }//GEN-LAST:event_search2ActionPerformed

    private void searchText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchText1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        department2 dep = new department2();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dep.setVisible(true);
                dep.setSize(1240,760);
                dep.setResizable(false);
            }
        });
    }

    login log;
    EditMenu e;
    EditDrink d;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JButton done1;
    private javax.swing.JButton done2;
    private javax.swing.JButton drinkMenu;
    private javax.swing.JButton foodMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea orderArea;
    private javax.swing.JButton search1;
    private javax.swing.JButton search2;
    private javax.swing.JTextField searchText;
    private javax.swing.JTextField searchText1;
    // End of variables declaration//GEN-END:variables
}
