/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package resturent;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class InerOrder extends javax.swing.JFrame {
 Connection co;
            Statement st;
    /**
     * Creates new form InerOrder
     */
    public InerOrder() {
        initComponents();
        drinkArea.setEditable(false);
        orderArea.setEditable(false);
        
        this.setSize(812,746);
        this.setResizable(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        orderNumber = new javax.swing.JTextField();
        orderText = new javax.swing.JTextField();
        drinkText = new javax.swing.JTextField();
        drinkNumber = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        drinkArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderArea = new javax.swing.JTextArea();
        addDrink = new javax.swing.JButton();
        addOrder = new javax.swing.JButton();
        tableNum = new javax.swing.JTextField();
        deleteOrder = new javax.swing.JButton();
        deleteDrink = new javax.swing.JButton();
        save = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("الطلبات الداخلية");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(289, 13, 179, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("الطلب ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(736, 150, 44, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("العدد ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(743, 198, 37, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("المشروبات ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(705, 265, 75, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("العدد ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(743, 313, 37, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("رقم الطاولة ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(701, 384, 79, 17);

        orderNumber.setBackground(new java.awt.Color(242, 238, 238));
        orderNumber.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        orderNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderNumberActionPerformed(evt);
            }
        });
        getContentPane().add(orderNumber);
        orderNumber.setBounds(645, 192, 48, 30);

        orderText.setBackground(new java.awt.Color(242, 238, 238));
        orderText.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        orderText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderTextActionPerformed(evt);
            }
        });
        getContentPane().add(orderText);
        orderText.setBounds(473, 144, 220, 30);

        drinkText.setBackground(new java.awt.Color(242, 238, 238));
        drinkText.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        drinkText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drinkTextActionPerformed(evt);
            }
        });
        getContentPane().add(drinkText);
        drinkText.setBounds(475, 259, 218, 30);

        drinkNumber.setBackground(new java.awt.Color(242, 238, 238));
        drinkNumber.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        drinkNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drinkNumberActionPerformed(evt);
            }
        });
        getContentPane().add(drinkNumber);
        drinkNumber.setBounds(645, 307, 48, 30);

        drinkArea.setBackground(new java.awt.Color(242, 238, 238));
        drinkArea.setColumns(20);
        drinkArea.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        drinkArea.setRows(5);
        jScrollPane1.setViewportView(drinkArea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(23, 419, 333, 257);

        orderArea.setBackground(new java.awt.Color(242, 238, 238));
        orderArea.setColumns(20);
        orderArea.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        orderArea.setRows(5);
        jScrollPane2.setViewportView(orderArea);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(23, 144, 333, 257);

        addDrink.setBackground(new java.awt.Color(102, 102, 102));
        addDrink.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        addDrink.setForeground(new java.awt.Color(255, 255, 255));
        addDrink.setText("إضافة");
        addDrink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDrinkActionPerformed(evt);
            }
        });
        getContentPane().add(addDrink);
        addDrink.setBounds(368, 259, 81, 30);

        addOrder.setBackground(new java.awt.Color(102, 102, 102));
        addOrder.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        addOrder.setForeground(new java.awt.Color(255, 255, 255));
        addOrder.setText("إضافة");
        addOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrderActionPerformed(evt);
            }
        });
        getContentPane().add(addOrder);
        addOrder.setBounds(368, 144, 81, 30);

        tableNum.setBackground(new java.awt.Color(242, 238, 238));
        tableNum.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tableNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableNumActionPerformed(evt);
            }
        });
        getContentPane().add(tableNum);
        tableNum.setBounds(631, 378, 65, 30);

        deleteOrder.setBackground(new java.awt.Color(102, 102, 102));
        deleteOrder.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        deleteOrder.setForeground(new java.awt.Color(255, 255, 255));
        deleteOrder.setText("حذف");
        deleteOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteOrderActionPerformed(evt);
            }
        });
        getContentPane().add(deleteOrder);
        deleteOrder.setBounds(368, 192, 81, 30);

        deleteDrink.setBackground(new java.awt.Color(102, 102, 102));
        deleteDrink.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        deleteDrink.setForeground(new java.awt.Color(255, 255, 255));
        deleteDrink.setText("حذف");
        deleteDrink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDrinkActionPerformed(evt);
            }
        });
        getContentPane().add(deleteDrink);
        deleteDrink.setBounds(368, 307, 81, 30);

        save.setBackground(new java.awt.Color(102, 102, 102));
        save.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setText("تخزين الطلب");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(519, 500, 123, 42);

        back.setBackground(new java.awt.Color(102, 102, 102));
        back.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("رجوع");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(374, 634, 98, 42);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(370, 360, 430, 10);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(370, 240, 430, 10);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resturent/الطلبات.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 820, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void orderNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orderNumberActionPerformed

    private void orderTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orderTextActionPerformed

    private void drinkTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drinkTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drinkTextActionPerformed

    private void drinkNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drinkNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drinkNumberActionPerformed

    private void tableNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tableNumActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
       
        tableNum.setText("");
        orderText.setText("");
        orderNumber.setText("");
        orderArea.setText("");
        drinkText.setText("");
        drinkNumber.setText("");
        drinkArea.setText("");
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed

try{
              DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            String host="jdbc:oracle:thin:@localhost:1522:orcl";
            String name= "project";
            String pass="123456";
             co=DriverManager.getConnection(host, name, pass);
             st=co.createStatement();
            String SQL ="insert into INERORDER values('"+this.tableNum.getText()+"','"+this.drinkArea.getText()+"','"+this.orderArea.getText()+"')";
           st.executeUpdate(SQL);
           co.commit();
           co.close();
        }catch(SQLException aa){
            
        }

        tableNum.setText("");
        orderText.setText("");
        orderNumber.setText("");
        orderArea.setText("");
        drinkText.setText("");
        drinkNumber.setText("");
        drinkArea.setText("");
    }//GEN-LAST:event_saveActionPerformed

    private void addOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrderActionPerformed
        if(orderText.getText().isEmpty())
            JOptionPane.showMessageDialog(this, "أضف طلب اولاً");
        else if(orderNumber.getText().isEmpty())
            JOptionPane.showMessageDialog(this, "أضف رقم");
        else {
            orderArea.append(orderText.getText()+" - "+orderNumber.getText()+"\n");
        }
        orderText.setText("");
        orderNumber.setText("");
    }//GEN-LAST:event_addOrderActionPerformed

    private void addDrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDrinkActionPerformed
       
        if(drinkText.getText().isEmpty())
            JOptionPane.showMessageDialog(this, "أضف طلب اولاً");
        else if(drinkNumber.getText().isEmpty())
            JOptionPane.showMessageDialog(this, "أضف رقم");
        else {
            drinkArea.append(drinkText.getText()+" - "+drinkNumber.getText()+"\n");
        }
        drinkText.setText("");
        drinkNumber.setText("");
    }//GEN-LAST:event_addDrinkActionPerformed

    private void deleteOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteOrderActionPerformed
       if(orderText.getText().isEmpty())
            JOptionPane.showMessageDialog(this, "أضف طلب اولاً");
       else {
           String a = orderArea.getText();
           String[] s = a.split("\n");
           orderArea.setText("");
           for(int i=0;i<s.length;i++){
               if(s[i].contains(orderText.getText())){
                   s[i] = "";
                   break;
               }
           }
           for(int i =0;i<s.length;i++){
               if(s[i] != "")
                   orderArea.append(s[i]+"\n");
           }
           
       }
       orderText.setText("");
       orderNumber.setText("");
    }//GEN-LAST:event_deleteOrderActionPerformed

    private void deleteDrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDrinkActionPerformed
        if(drinkText.getText().isEmpty())
            JOptionPane.showMessageDialog(this, "أضف طلب اولاً");
       else {
           String a = drinkArea.getText();
           String[] s = a.split("\n");
           drinkArea.setText("");
           for(int i=0;i<s.length;i++){
               if(s[i].contains(drinkText.getText())){
                   s[i] = "";
                   break;
               }
           }
           for(int i =0;i<s.length;i++){
               if(s[i] != "")
                   drinkArea.append(s[i]+"\n");
           }
           
       }
       drinkText.setText("");
       drinkNumber.setText("");
    }//GEN-LAST:event_deleteDrinkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        InerOrder in = new InerOrder();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                in.setVisible(true);
                in.setSize(812,746);
                in.setResizable(false);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDrink;
    private javax.swing.JButton addOrder;
    private javax.swing.JButton back;
    private javax.swing.JButton deleteDrink;
    private javax.swing.JButton deleteOrder;
    private javax.swing.JTextArea drinkArea;
    private javax.swing.JTextField drinkNumber;
    private javax.swing.JTextField drinkText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea orderArea;
    private javax.swing.JTextField orderNumber;
    private javax.swing.JTextField orderText;
    private javax.swing.JButton save;
    private javax.swing.JTextField tableNum;
    // End of variables declaration//GEN-END:variables
}
