/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package resturent;

import static com.sun.glass.events.DndEvent.EXIT;

/**
 *
 * @author Admin
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        this.setSize(1260,740);
                this.setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        empButton = new javax.swing.JButton();
        manButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 255));
        jLabel2.setText("اختر القسم الذي تعمل به :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(830, 260, 230, 22);

        empButton.setBackground(new java.awt.Color(153, 0, 0));
        empButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        empButton.setForeground(new java.awt.Color(255, 255, 255));
        empButton.setText("الإستقبال");
        empButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empButtonActionPerformed(evt);
            }
        });
        getContentPane().add(empButton);
        empButton.setBounds(810, 350, 130, 40);

        manButton.setBackground(new java.awt.Color(153, 0, 0));
        manButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        manButton.setForeground(new java.awt.Color(255, 255, 255));
        manButton.setText("المطبخ");
        manButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manButtonActionPerformed(evt);
            }
        });
        getContentPane().add(manButton);
        manButton.setBounds(810, 460, 130, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resturent/index1.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 1260, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void empButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empButtonActionPerformed
        dep1 = new department1();
        dep1.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_empButtonActionPerformed

    private void manButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manButtonActionPerformed
        dep2 = new department2();
        dep2.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_manButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        login log = new login();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                log.setVisible(true);
                log.setSize(1260,740);
                log.setResizable(false);
            }
        });
    }
    
    
   department1 dep1 ;
    
    department2 dep2 ;
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton empButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton manButton;
    // End of variables declaration//GEN-END:variables
}
