/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package resturent;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import oracle.jdbc.pool.OracleDataSource;

/**
 *
 * @author Admin
 */
public class MainOrder extends javax.swing.JFrame {
private String A;
    Connection co;
            Statement st;
             DefaultListModel mod = new DefaultListModel();


    /**
     * Creates new form MainOrder
     */
    public MainOrder() {
        initComponents();
         this.setSize(693,670);
         this.setResizable(false);
          foodList.setModel(mod);
         try{
            
            //  DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            OracleDataSource oda = new OracleDataSource();
            String host="jdbc:oracle:thin:@localhost:1522:orcl";
            String name= "project";
            String pass="123456";
            oda.setURL(host);
            oda.setUser(name);
            oda.setPassword(pass);
              co=oda.getConnection();
             st=co.createStatement(/*ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE*/);
            ResultSet rt=st.executeQuery("Select * from FOODMENU");
           
           while( rt.next()){
             mod.addElement(rt.getString(1));
               
           }
           
            co.close();
           
        }catch(Exception aa){
            Logger.getLogger(Dates.class.getName()).log(Level.SEVERE,null,aa);
        }
    }
       public void setA(String ad) {
		A=ad;
	}
	public String getA() {
		return A;
	}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        foodList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        addOrder = new javax.swing.JButton();
        deleteOrder = new javax.swing.JButton();
        orderText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        orderNumber = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        orderArea = new javax.swing.JTextArea();
        save = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().setLayout(null);

        foodList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(foodList);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(12, 98, 240, 470);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("قائمة الطعام");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(280, 10, 150, 29);

        back.setBackground(new java.awt.Color(102, 102, 102));
        back.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("رجوع");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(280, 520, 90, 40);

        addOrder.setBackground(new java.awt.Color(102, 102, 102));
        addOrder.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        addOrder.setForeground(new java.awt.Color(255, 255, 255));
        addOrder.setText("إضافة");
        addOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrderActionPerformed(evt);
            }
        });
        getContentPane().add(addOrder);
        addOrder.setBounds(260, 100, 81, 30);

        deleteOrder.setBackground(new java.awt.Color(102, 102, 102));
        deleteOrder.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        deleteOrder.setForeground(new java.awt.Color(255, 255, 255));
        deleteOrder.setText("حذف");
        deleteOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteOrderActionPerformed(evt);
            }
        });
        getContentPane().add(deleteOrder);
        deleteOrder.setBounds(260, 150, 81, 30);

        orderText.setBackground(new java.awt.Color(242, 238, 238));
        orderText.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        orderText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderTextActionPerformed(evt);
            }
        });
        getContentPane().add(orderText);
        orderText.setBounds(360, 100, 220, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("الطلب ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(630, 110, 44, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("العدد ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(630, 150, 37, 17);

        orderNumber.setBackground(new java.awt.Color(242, 238, 238));
        orderNumber.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        orderNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderNumberActionPerformed(evt);
            }
        });
        getContentPane().add(orderNumber);
        orderNumber.setBounds(530, 150, 48, 30);

        orderArea.setColumns(20);
        orderArea.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        orderArea.setRows(5);
        jScrollPane3.setViewportView(orderArea);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(260, 200, 240, 270);

        save.setBackground(new java.awt.Color(102, 102, 102));
        save.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setText("تخزين الطلب");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(530, 270, 130, 42);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resturent/الطلبات.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 740, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void addOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrderActionPerformed
        if(orderText.getText().isEmpty())
        JOptionPane.showMessageDialog(this, "أضف طلب اولاً");
        else if(orderNumber.getText().isEmpty())
        JOptionPane.showMessageDialog(this, "أضف رقم");
        else {
            orderArea.append(orderText.getText()+" - "+orderNumber.getText()+"\n");
        }
        orderText.setText("");
        orderNumber.setText("");
    }//GEN-LAST:event_addOrderActionPerformed

    private void deleteOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteOrderActionPerformed
        if(orderText.getText().isEmpty())
        JOptionPane.showMessageDialog(this, "أضف طلب اولاً");
        else {
            String a = orderArea.getText();
            String[] s = a.split("\n");
            orderArea.setText("");
            for(int i=0;i<s.length;i++){
                if(s[i].contains(orderText.getText())){
                    s[i] = "";
                    break;
                }
            }
            for(int i =0;i<s.length;i++){
                if(s[i] != "")
                orderArea.append(s[i]+"\n");
            }

        }
        orderText.setText("");
        orderNumber.setText("");
    }//GEN-LAST:event_deleteOrderActionPerformed

    private void orderTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orderTextActionPerformed

    private void orderNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orderNumberActionPerformed
    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        setA(orderArea.getText());
        orderArea.setText("");
        orderNumber.setText("");
        orderText.setText("");
    }//GEN-LAST:event_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       MainOrder main = new MainOrder();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                main.setVisible(true);
                main.setSize(693,670);
                main.setResizable(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addOrder;
    private javax.swing.JButton back;
    private javax.swing.JButton deleteOrder;
    private javax.swing.JList<String> foodList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea orderArea;
    private javax.swing.JTextField orderNumber;
    private javax.swing.JTextField orderText;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
