/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package resturent;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import oracle.jdbc.pool.OracleDataSource;

/**
 *
 * @author Admin
 */
public class showDelivery extends javax.swing.JFrame {
 Connection co;
            Statement st;
    /**
     * Creates new form showDelivery
     */
    public showDelivery() {
        initComponents();
        this.setSize(840,720);
        this.setResizable(false);
        DeliveryShow.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DeliveryShow = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        NameSearch = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        back = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("عرض الطلبات");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(359, 13, 117, 22);

        DeliveryShow.setColumns(20);
        DeliveryShow.setRows(5);
        jScrollPane1.setViewportView(DeliveryShow);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(12, 73, 378, 589);

        jButton1.setBackground(new java.awt.Color(204, 0, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("عرض كل الطلبات");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(624, 177, 169, 34);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("البحث عن طلب (حسب الاسم) :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(585, 280, 208, 17);

        search.setBackground(new java.awt.Color(204, 0, 51));
        search.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setText("بحث");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search);
        search.setBounds(723, 332, 70, 25);

        NameSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameSearchActionPerformed(evt);
            }
        });
        getContentPane().add(NameSearch);
        NameSearch.setBounds(496, 332, 215, 25);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 0));
        jLabel8.setText("حذف الطلب :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(707, 439, 86, 17);

        delete.setBackground(new java.awt.Color(204, 0, 51));
        delete.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("حذف");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete);
        delete.setBounds(560, 436, 85, 25);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(397, 399, 414, 10);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(397, 252, 414, 10);

        back.setBackground(new java.awt.Color(204, 0, 51));
        back.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("رجوع");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(420, 615, 100, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resturent/index2.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 850, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        try{
            //  DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            OracleDataSource oda = new OracleDataSource();
            String host="jdbc:oracle:thin:@localhost:1522:orcl";
            String name= "project";
            String pass="123456";
            oda.setURL(host);
            oda.setUser(name);
            oda.setPassword(pass);
              co=oda.getConnection();
             st=co.createStatement(/*ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE*/);
            ResultSet rt=st.executeQuery("Select * from DELIVERY");
            this.DeliveryShow.setText("Name"+"          "+"Phone"+"            "+"Address 1"+"           "+"Address 2"+"          "+"Order"+"       "+"Drink"+"\n");
            this.DeliveryShow.append("-----------------------------------------------------------------------------------------"+"\n");
           while( rt.next()){
            String a= rt.getString(1);
            int b= rt.getInt(2);
            String c= rt.getString(3);
            String d= rt.getString(4);
            String e= rt.getString(5);
            String f= rt.getString(6);
            this.DeliveryShow.append(a+"          "+b+"          "+c+"          "+d+"             "+e+"           "+f+"\n");
           }
            co.close();
           
        }catch(Exception aa){
            Logger.getLogger(Dates.class.getName()).log(Level.SEVERE,null,aa);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
         try{
            //  DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            OracleDataSource oda = new OracleDataSource();
            String host="jdbc:oracle:thin:@localhost:1522:orcl";
            String name= "project";
            String pass="123456";
            oda.setURL(host);
            oda.setUser(name);
            oda.setPassword(pass);
              co=oda.getConnection();
             st=co.createStatement(/*ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE*/);
            ResultSet rt=st.executeQuery("Select * from DELIVERY where ALL_NAME='"+this.NameSearch.getText()+"'");
            this.DeliveryShow.setText("Name"+"          "+"Phone"+"            "+"Address 1"+"           "+"Address 2"+"          "+"Order"+"         "+"Drink"+"\n");
            this.DeliveryShow.append("-----------------------------------------------------------------------------------------"+"\n");
           while( rt.next()){
            String a= rt.getString(1);
            int b= rt.getInt(2);
            String c= rt.getString(3);
            String d= rt.getString(4);
            String e= rt.getString(5);
            String f= rt.getString(6);
            this.DeliveryShow.append(a+"          "+b+"          "+c+"          "+d+"              "+e+"   " +f+"\n");
           }
            co.close();
           
        }catch(Exception aa){
            Logger.getLogger(Dates.class.getName()).log(Level.SEVERE,null,aa);
        }
    }//GEN-LAST:event_searchActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
         try{
              DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            String host="jdbc:oracle:thin:@localhost:1522:orcl";
            String name= "project";
            String pass="123456";
             co=DriverManager.getConnection(host, name, pass);
             st=co.createStatement(/*ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE*/);
            String SQL ="DELETE FROM DELIVERY where ALL_NAME='"+this.NameSearch.getText()+"'";
           st.executeUpdate(SQL);
           co.commit();
           co.close();
        }catch(SQLException aa){
            
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        DeliveryShow.setText("");
        NameSearch.setText("");
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void NameSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        showDelivery SDel = new showDelivery();
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SDel.setVisible(true);
                SDel.setSize(840,720);
                SDel.setResizable(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea DeliveryShow;
    private javax.swing.JTextField NameSearch;
    private javax.swing.JButton back;
    private javax.swing.JButton delete;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton search;
    // End of variables declaration//GEN-END:variables
}
